In [0]:
import pandas as pd
import numpy as np

In [0]:
pd.set_option('display.float_format', '{:.2f}'.format)
np.set_printoptions(precision=1)

## Concatenate Numpy
---

In [8]:
x1 = np.random.rand(2, 5) * 10
x1

array([[5.5, 8.2, 8.4, 7.2, 7.6],
       [4.4, 5. , 5.6, 6.5, 5.5]])

In [9]:
x2 = np.random.rand(2, 5) * -1
x2 

array([[-0.6, -0.7, -0.9, -0.2, -0.9],
       [-0.9, -0.3, -0.1, -0.6, -0.1]])

In [10]:
np.concatenate([x1, x2])

array([[ 5.5,  8.2,  8.4,  7.2,  7.6],
       [ 4.4,  5. ,  5.6,  6.5,  5.5],
       [-0.6, -0.7, -0.9, -0.2, -0.9],
       [-0.9, -0.3, -0.1, -0.6, -0.1]])

In [11]:
np.concatenate([x1, x2], axis=1)

array([[ 5.5,  8.2,  8.4,  7.2,  7.6, -0.6, -0.7, -0.9, -0.2, -0.9],
       [ 4.4,  5. ,  5.6,  6.5,  5.5, -0.9, -0.3, -0.1, -0.6, -0.1]])

## Concat Pandas (Series)
---

In [15]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   5.49
b   8.22
c   8.42
d   7.21
e   7.62
dtype: float64

In [16]:
s2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   -0.55
d   -0.66
e   -0.91
f   -0.23
g   -0.94
dtype: float64

In [19]:
pd.concat([s1, s2]) # Index keys repeated

a    5.49
b    8.22
c    8.42
d    7.21
e    7.62
c   -0.55
d   -0.66
e   -0.91
f   -0.23
g   -0.94
dtype: float64

In [21]:
pd.concat([s1, s2], axis=1) # Concat using index keys

0     1
a 5.49   nan
b 8.22   nan
c 8.42 -0.55
d 7.21 -0.66
e 7.62 -0.91
f  nan -0.23
g  nan -0.94

In [27]:
s1.reset_index() # Resets index. Adds column "index"

index    0
0     a 5.49
1     b 8.22
2     c 8.42
3     d 7.21
4     e 7.62

In [28]:
s1.reset_index(drop=True) # The same but without "index" column

0   5.49
1   8.22
2   8.42
3   7.21
4   7.62
dtype: float64

## Concat pandas (DataFrames)
---

In [30]:
df1 = pd.DataFrame(np.random.rand(3, 2)*10, columns=['a', 'b'])
df1

a    b
0 8.97 0.09
1 2.43 2.84
2 0.82 5.63

In [31]:
df2 = pd.DataFrame(np.random.rand(3, 2)*-1, columns=['a', 'b'], index=[2, 3, 4])
df2

a     b
2 -0.36 -0.16
3 -0.50 -0.09
4 -0.47 -0.01

In [35]:
pd.concat([df1, df2]) # Index keys repeated

a     b
0  8.97  0.09
1  2.43  2.84
2  0.82  5.63
2 -0.36 -0.16
3 -0.50 -0.09
4 -0.47 -0.01

In [42]:
pd.concat([df1, df2], axis=1) # Concat using index keys.

a    b     a     b
0 8.97 0.09   nan   nan
1 2.43 2.84   nan   nan
2 0.82 5.63 -0.36 -0.16
3  nan  nan -0.50 -0.09
4  nan  nan -0.47 -0.01

In [48]:
# Join Inner concats just common elements between dataframes
pd.concat([df1, df2], axis=1, join='inner')

a    b     a     b
2 0.82 5.63 -0.36 -0.16

In [51]:
df2.reset_index() # Reset index. Added "index" column.

index     a     b
0      2 -0.36 -0.16
1      3 -0.50 -0.09
2      4 -0.47 -0.01

In [52]:
df2.reset_index(drop=True) # The same but without "index" column.

a     b
0 -0.36 -0.16
1 -0.50 -0.09
2 -0.47 -0.01

## Append Pandas (DataFrames)
---

In [53]:
df1.append(df2)

a     b
0  8.97  0.09
1  2.43  2.84
2  0.82  5.63
2 -0.36 -0.16
3 -0.50 -0.09
4 -0.47 -0.01

In [57]:
df1.T.append(df2.T).T

a    b     a     b
0 8.97 0.09   nan   nan
1 2.43 2.84   nan   nan
2 0.82 5.63 -0.36 -0.16
3  nan  nan -0.50 -0.09
4  nan  nan -0.47 -0.01

## Merge Pandas (DataFrames)
---